# Generated by Django 6.0.6 on 2026-07-01 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Match expires if no message sent within 48 hours.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CollaborationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1 to 5 star rating.')),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='matches.collaborationsession')),
            ],
            options={
                'db_table': 'matches_collab_rating',
                'unique_together': {('session', 'rated_by')},
            },
        ),
    ]
