# Generated by Django 6.0.6 on 2026-08-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_expires_at_match_is_expired_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('swipe_match', 'Swipe Match'), ('project_application', 'Project Application'), ('project_invitation', 'Project Invitation'), ('direct_hire', 'Direct Hire'), ('cofounder_match', 'Co-Founder Match')], default='swipe_match', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='projects.project'),
        ),
    ]
