# Generated by Django 6.0.6 on 2026-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_name',
            field=models.CharField(default='lifetime', max_length=50),
        ),
    ]
