# Generated by Django 6.0.6 on 2026-06-24 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_initial'),
        ('swipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swipeaction',
            name='swiper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipeaction',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swipefilter',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='swipe_filters', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='swipefilter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swipeaction',
            unique_together={('swiper', 'target')},
        ),
    ]
