# Generated by Django 6.0.6 on 2026-08-08 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0003_skillmatchscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['swiper', 'action'], name='swipe_actio_swiper__fcd235_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['target', 'action'], name='swipe_actio_target__d12b07_idx'),
        ),
        migrations.AddIndex(
            model_name='swipeaction',
            index=models.Index(fields=['swiper', 'target'], name='swipe_actio_swiper__c7ca3f_idx'),
        ),
    ]
