# Generated by Django 6.0.6 on 2026-07-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience_gained', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='portfolio_media/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='profiles.freelancerprofile')),
            ],
            options={
                'db_table': 'profiles_portfolio_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
