# Generated by Django 6.0.6 on 2026-07-26 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_portfolioitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.portfolioitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_portfolio_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profiles.portfolioitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_portfolio_like',
                'unique_together': {('item', 'user')},
            },
        ),
    ]
