# Generated by Django 6.0.6 on 2026-07-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_portfolioitemcomment_portfolioitemlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio_custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='portfolio_style',
            field=models.CharField(blank=True, default='modern_glass', max_length=50),
        ),
    ]
