# Generated by Django 6.0.6 on 2026-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_freelancerprofile_portfolio_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='avatar_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
