# Generated by Django 6.0.6 on 2026-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_companyprofile_logo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='english_fluency',
            field=models.CharField(blank=True, default='fluent', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='hours_per_week',
            field=models.CharField(blank=True, default='more_than_30', max_length=50),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='video_intro_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
