# Generated by Django 6.0.6 on 2026-08-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_freelancerprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='code_language',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
