# Generated by Django 6.0.6 on 2026-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_portfolioitem_code_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='code_snippet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
