version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../.env
    environment:
      - PORT=8000
    expose:
      - "8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
