# Generated by Django 6.0.6 on 2026-06-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_block_list',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('inappropriate_content', 'Inappropriate Content'), ('fake_profile', 'Fake Profile'), ('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('other', 'Other')], default='other', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('actioned', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moderation_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_count', models.PositiveSmallIntegerField(default=0)),
                ('is_temp_banned', models.BooleanField(default=False)),
                ('temp_ban_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moderation_user_strike',
            },
        ),
    ]
